### ISSUE TITLE
face_verification make failed

### ISSUE THREAD

**Issue by wxhhhhh** [acsl-technion/eleos#2]
when make the face_verification, it turns out:

untrusted/face_verification/face_verification.o: In function `populate_database(hash_t*, char const*, int*)':
face_verification.cpp:(.text+0x6ce): undefined reference to `sgx_init_crypto_lib'
untrusted/face_verification/face_verification.o: In function `workload_face_verification(void*)':
face_verification.cpp:(.text+0xaeb): undefined reference to `sgx_aes_ctr_decrypt'
face_verification.cpp:(.text+0xb6e): undefined reference to `sgx_aes_ctr_encrypt'
collect2: error: ld returned 1 exit status

I guess '-L/home/user/experiments-meni/graphene-bugfix/graphene/AptrLib/ippcp -lcrypto' in the sgx_u.mk is the problem
How to fix it?

**Comment by Bonjourz** [comment]
I meet the same problem... Is anybody here?

**Comment by shmeni** [comment]
Hey, I've pushed a fix for the compilation error. Please try it now by following the instructions at the README file.

**Comment by Bonjourz** [comment]
I can compile them successfully now, thank you!

**Comment by Bonjourz** [comment]
It works. Thank you!
