### ISSUE TITLE
APTR_RANDOM_ACCESS

### ISSUE THREAD

**Issue by andrewzigerelli** [acsl-technion/eleos#4]
Is this for  the sub page direct access? I've been trying to read your code a little over the past few days.

Thanks, very good work!

**Comment by shmeni** [comment]
Thank you for your kind words. 
Yes, the APTR_RANDOM_ACCESS definition enables sub-page direct access. 
Please note, however, that in the current implementation this definition is coupled with the SUB_PAGE_COUNT_LOG definition, which is used to identify how many sub-pages are part a page. 
The default configuration is for a page size of 4KB and 4 sub-pages in a page, meaning a sub-page size would be 1KB. This is all controlled by software so should be easy to change if you'd like to use different numbers.

**Comment by andrewzigerelli** [comment]
Forgot to close this, sorry! Trying to catch up on the follow up works
